# PyTorch Basics - Tensor Operations Part 2

In [1]:
import torch
import numpy as np

Creating two tensors a and b

In [2]:
a = torch.tensor([1.,2.,3.])
b = torch.tensor([4.,5.,6.])

Multiplying the two tensors

In [3]:
a * b

tensor([ 4., 10., 18.])

Using .dot to find the dot product of a and b

In [4]:
a.dot(b)

tensor(32.)

Creating a new tensors that is 2d

In [5]:
a = torch.tensor([[0,2,4],[1,3,5]])

In [6]:
a

tensor([[0, 2, 4],
        [1, 3, 5]])

Creating a new tensors that is 2d

In [7]:
b = torch.tensor([[6,7],[8,9],[10,11]])

In [8]:
b

tensor([[ 6,  7],
        [ 8,  9],
        [10, 11]])

Using torch.mm to do matrix multiplication on a and b

In [9]:
torch.mm(a,b)

tensor([[56, 62],
        [80, 89]])

Creating a new tensor

In [10]:
x = torch.tensor([2.,3.,4.,5.])

Using .norm() to find the vector norm

In [11]:
x.norm()

tensor(7.3485)

Using .numel() to find the number of elements

In [12]:
x.numel()

4