# PyTorch Basics - Tensor Basics Part 2

In [1]:
import torch
import numpy as np

Creating a new array

In [2]:
new_arr = np.array([1,2,3])

Creating a tensor with lower case t, this gives a tensor of type int32

In [3]:
torch.tensor(new_arr)

tensor([1, 2, 3], dtype=torch.int32)

Creating a tensor with upper case t, this gives a tensor of type float

In [4]:
torch.Tensor(new_arr)

tensor([1., 2., 3.])

Using torch.empty to create an empty tensor

In [5]:
torch.empty(2,2)

tensor([[8.9082e-39, 5.9694e-39],
        [1.0286e-38, 8.9081e-39]])

Using torch.zeros to create a tensor of zeros

In [8]:
torch.zeros(4,3,dtype=torch.int32)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

Using torch.ones to create a tensor of ones

In [9]:
torch.ones(4,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

Using torch.arange to create a tensor from 0 to 18 by steps of 2

In [10]:
torch.arange(0,18,2)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

Using torch.reshape to reshape the tensor

In [11]:
torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

Using torch.linspace to create a tensor of linear space

In [13]:
torch.linspace(0,18,12).reshape(3,4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

Using torch.rand to create a tensor of random numbers between 0 and 1

In [14]:
torch.rand(4,3)

tensor([[0.5527, 0.6227, 0.1381],
        [0.1068, 0.9396, 0.6270],
        [0.0892, 0.7832, 0.6945],
        [0.3026, 0.5413, 0.8580]])

Using torch.randn to create a tensor of random numbers from a normal distribution

In [15]:
torch.randn(5,5)

tensor([[ 0.9020,  0.2641,  0.5703,  1.9832,  0.0254],
        [ 1.8686,  1.6440, -1.7928,  0.1906,  0.0060],
        [-0.3619,  0.1264,  0.1968,  0.0579, -0.1527],
        [ 0.8740, -0.6043, -0.0936, -0.0637,  1.4468],
        [ 1.1826, -1.5834,  0.5223,  0.4088,  1.6514]])

Using torch.randint to create a tensor of random integers from 0 to 10

In [16]:
torch.randint(low=0, high=10,size=(5,5))

tensor([[5, 1, 6, 1, 0],
        [9, 0, 7, 1, 3],
        [3, 2, 1, 0, 4],
        [2, 2, 8, 3, 4],
        [3, 6, 1, 0, 1]])

Creating a tensor of zeros

In [17]:
x = torch.zeros(2,5)

In [18]:
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

Using torch.rand_like to create a tensor of random numbers the same shape as tensor x

In [19]:
torch.rand_like(x)

tensor([[0.2065, 0.2309, 0.6326, 0.3953, 0.4685],
        [0.8294, 0.0467, 0.1164, 0.2470, 0.5354]])

Using torch.randn_like to create a tensor of random numbers from a normal distribution the same shape as tensor x

In [20]:
torch.randn_like(x)

tensor([[ 0.3166, -0.6783,  1.2469, -0.0829, -0.7224],
        [ 0.1548, -0.4218, -2.0147, -1.1262,  0.2149]])

Using torch.randint_like to create a tensor of random integers the same shape as tensor x

In [21]:
torch.randint_like(x,low=0,high=10)

tensor([[5., 1., 4., 0., 2.],
        [3., 1., 2., 7., 0.]])

using torch.manual_seed to declare a seed for random numbers 

In [23]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])