# PyTorch Basics - Tensor Basics Part 1

Import PyTorch

In [1]:
import torch
import numpy as np

Checking the version number

In [2]:
torch.__version__

'1.1.0'

Creating a NumPy array

In [3]:
arr = np.array([1,2,3,4,5])

Creating a tensor from that array

In [5]:
x = torch.from_numpy(arr)

Checking the type

In [6]:
type(x)

torch.Tensor

Another way to create a tensor

In [7]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

Creating a 2d array

In [8]:
arr_2d = np.arange(0.0,12.0)

In [9]:
arr_2d = arr_2d.reshape(4,3)

In [10]:
arr_2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

Creating a 2d tensor from the 2d array

In [11]:
x2 = torch.from_numpy(arr_2d)

In [12]:
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

Changing a value in the array

In [13]:
arr[0] = 99

In [14]:
arr

array([99,  2,  3,  4,  5])

The tensor is now also changed

In [15]:
x

tensor([99,  2,  3,  4,  5], dtype=torch.int32)

In [16]:
myarr = np.arange(0,10)

To avoid this, use torch.tensor()

In [17]:
mytensor = torch.tensor(myarr)