# PyTorch Basics - Tensor Operations Part 1

In [1]:
import torch
import numpy as np

Creating a tensor from arange and reshaping it

In [2]:
x = torch.arange(6).reshape(3,2)

In [3]:
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

Getting the tensor value at position 1,1

In [4]:
x[1,1]

tensor(3)

Getting the tensor values of all rows in column 1

In [5]:
x[:,1]

tensor([1, 3, 5])

Same thing except using slice to keep them in different rows

In [6]:
x[:,1:]

tensor([[1],
        [3],
        [5]])

Creating a new tensor

In [7]:
x = torch.arange(10)

In [8]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Using .view to reshape the tensor

In [9]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [10]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Using .reshape to reshape the tensor, is the same as .view

In [11]:
x.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [12]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Saving the reshaped tensor

In [13]:
x = x.reshape(2,5)

In [14]:
x

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

Creating a new tensor

In [15]:
x = torch.arange(10)

In [16]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Saving the .view reshaped tensor

In [17]:
z = x.view(2,5)

In [18]:
z

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

Changing the value of tensor x position 0 to 999

In [19]:
x[0] = 999

In [20]:
x

tensor([999,   1,   2,   3,   4,   5,   6,   7,   8,   9])

Tensor z is now also updated with the change

In [21]:
z

tensor([[999,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

creating a new tensor

In [22]:
x = torch.arange(10)

In [23]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In .view using -1 to autofill the reshape

In [24]:
x.view(2,-1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [25]:
x.view(-1,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

Creating two tesnors a and b

In [26]:
a = torch.tensor([1.,2.,3.])

In [27]:
b = torch.tensor([4.,5.,6.])

Adding the two tensors using +

In [28]:
a + b

tensor([5., 7., 9.])

Adding the two tensors using .add

In [29]:
torch.add(a,b)

tensor([5., 7., 9.])

using .mul to multiple the two tensors

In [30]:
a.mul(b)

tensor([ 4., 10., 18.])

Nothing changes in a after .mul

In [31]:
a

tensor([1., 2., 3.])

Using .mul_ will make the operation save

In [32]:
a.mul_(b)

tensor([ 4., 10., 18.])

In [33]:
a

tensor([ 4., 10., 18.])