# NumPy Crash Course - Operations

In [1]:
import numpy as np

Creating an array using arange

In [2]:
arr = np.arange(0,10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Adding 100 to every value in the array

In [4]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

Adding the array to the array

In [5]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

Taking the square root of the array

In [6]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

Finding the sine of the array

In [8]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

Finding the sum of the values in the array

In [9]:
arr.sum()

45

Finding the mean of the values in the array

In [10]:
arr.mean()

4.5

Creating a 2d array

In [16]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

Finding the shape of the 2d array

In [17]:
arr_2d.shape

(3, 4)

Finding the sum of the values in the array

In [18]:
arr_2d.sum()

78

Using axis=0 as the paramater in the sum finds the sum of the columns 

In [19]:
arr_2d.sum(axis=0)

array([15, 18, 21, 24])

Using axis=1 as the paramater in the sum finds the sum of the columns

In [20]:
arr_2d.sum(axis=1)

array([10, 26, 42])