# NumPy Crash Course - Arrays Part 1 

Import NumPy

In [46]:
import numpy as np

Create a list with values 

In [47]:
mylist = [1,2,3]

By default it is of type list

In [48]:
type(mylist)

list

Using np.array can turn the list into an array

In [49]:
arr = np.array(mylist)

In [50]:
arr

array([1, 2, 3])

Create a list of lists

In [51]:
mylist2 = [[1,2,3], [4,5,6], [7,8,9]]

In [52]:
mylist2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

Using np.array on a list of lists can turn it into a matrix

In [53]:
matrix = np.array(mylist2)

In [54]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Using .shape can get the shape of the matrix, this is a 3 x 3 matrix

In [55]:
matrix.shape

(3, 3)

Using np.arange() will return evenly spaced values between a given interval 

In [56]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

The third parameter is the interval 

In [57]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

Using np.zeros returns a list of zeroes as floats, parameter is how many

In [58]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

This can also be done as a matrix by giving the shape of the matrix

In [59]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Using np.ones does the same as np.zeros except with 1s

In [60]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In NumPy you can also do operations when crerating arrays or matrices 

In [61]:
np.ones((5,5)) + 4

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [62]:
np.ones(4) * 100

array([100., 100., 100., 100.])

Using np.linspace returns a linear space array meaning evenly spaced numbers over a specified interval. (start, stop, number of vlues in the array)

In [63]:
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

Using np.eye return an identity matrix of the size given

In [64]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [65]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])