# NumPy Crash Course - Index Selection

In [1]:
import numpy as np

Creating an array using arange

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Get the value at index 8 of the array

In [4]:
arr[8]

8

Get the values from index 1 up to but not including index 5

In [5]:
arr[1:5]

array([1, 2, 3, 4])

Get the values from the start up to index 5

In [6]:
arr[:5]

array([0, 1, 2, 3, 4])

Get the values from index 5 to the end

In [7]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

Add 100 to every value in the array

In [8]:
arr + 100


array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

Divide every value by 2

In [10]:
arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

Every value in the array squared 

In [11]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

Slice the array from index 0 up to index 6

In [12]:
slice_of_arr = arr[0:6]

In [13]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

Make every value in the array 99

In [14]:
slice_of_arr[:] = 99

In [15]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

When slicing the array it still references back to the original array 

In [16]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

To not references back to the original array use .copy() to make a copy of it

In [18]:
arr_copy = arr.copy()

In [19]:
arr_copy[:] = 100

In [20]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [21]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Creating a 2d array

In [22]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [23]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

Get the first row of the 2d array

In [25]:
arr_2d[1]

array([20, 25, 30])

To get a value in the 2d array either use [x,y] or [x][y]

In [26]:
arr_2d[1,1]

25

In [27]:
arr_2d[1][1]

25

Get the first two rows in the 2d array

In [28]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

Get the first two rows and everything from index 1 and on in the 2d array

In [29]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

Creating a new array

In [36]:
arr = np.arange(1,11)

Return True are false for if the value is greater than 4

In [37]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [38]:
bool_arr = arr > 4

In [39]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [40]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [41]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])