# NumPy Crash Course - Arrays Part 2

In [1]:
import numpy as np

Using np.random.rand returns a random number between 0 and 1

In [2]:
np.random.rand(1)

array([0.09108835])

Putting in a parameter gives you that many random numbers 

In [3]:
np.random.rand(4)

array([0.25876339, 0.23995257, 0.40496074, 0.20843125])

A matrix of random numbers can also be created

In [4]:
np.random.rand(5,5)

array([[0.97451151, 0.02342335, 0.4364361 , 0.27957354, 0.20501072],
       [0.33511272, 0.72292819, 0.77770596, 0.55365449, 0.80545752],
       [0.27912161, 0.84681514, 0.0225367 , 0.43724651, 0.69292137],
       [0.78762976, 0.88172596, 0.16998914, 0.41720105, 0.0760047 ],
       [0.23335124, 0.95456259, 0.05361433, 0.94236322, 0.68875633]])

Using np.random.randn gives a random number from the “standard normal” distribution

In [5]:
np.random.randn(1)

array([2.89082764])

In [6]:
np.random.randn(10)

array([ 0.03388686, -0.30498382, -0.55910458,  0.17655683,  0.47280392,
       -0.39593009, -1.96439919,  1.0836176 , -0.87037615,  1.31344668])

Using np.random.randint gives a random integer between the numbers given

In [7]:
np.random.randint(1,100)

4

Thirs parameter is how many random integers

In [8]:
np.random.randint(1,100,10)

array([88, 97, 72, 23, 37, 85, 15, 27, 59, 40])

np.random.seed makes it if someone else uses the same seed they will get the same random numbers

In [11]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

Creating an array with arange

In [12]:
arr = np.arange(25)

In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

Creating an array with random numbers

In [14]:
ranarr = np.random.randint(0,50,10)

In [15]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

Finding the shape of the array

In [16]:
arr.shape

(25,)

Using .reshape will reshape the array into a matrix put only if the two turns when multiplied equals the number of values

In [17]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

Using .max() finds the max value in the array

In [18]:
ranarr.max()

39

Using .min() finds the min value in the array

In [19]:
ranarr.min()

2

Using .argmax() finds the index of the max value in the array

In [20]:
ranarr.argmax()

7

Using .argmin() finds the index of the min value in the array

In [21]:
ranarr.argmin()

9

Using .dtype returns 

In [22]:
ranarr.dtype

dtype('int32')