# ANN - PyTorch Gradients

In [1]:
import torch

Creating a tensor that requires grad

In [2]:
x = torch.tensor(2.0,requires_grad=True)

Creating a function

In [3]:
y = 2*x**4 + x**3 + 3*x**2 + 5*x + 1

In [4]:
print(y)

tensor(63., grad_fn=<AddBackward0>)


Using .backward to Computes the sum of gradients 

In [5]:
y.backward()

In [6]:
x.grad

tensor(93.)

Creating a tensor

In [8]:
x = torch.tensor([[1.,2.,3.],[3.,2.,1.]],requires_grad=True)

In [9]:
print(x)

tensor([[1., 2., 3.],
        [3., 2., 1.]], requires_grad=True)


Creating a function

In [10]:
y = 3*x + 2

In [11]:
print(y)

tensor([[ 5.,  8., 11.],
        [11.,  8.,  5.]], grad_fn=<AddBackward0>)


Creating a function

In [12]:
z = 2*y**2

In [13]:
print(z)

tensor([[ 50., 128., 242.],
        [242., 128.,  50.]], grad_fn=<MulBackward0>)


Finding the mean of the matrix

In [14]:
out = z.mean()

In [15]:
print(out)

tensor(140., grad_fn=<MeanBackward0>)


Perform back-propagation 

In [16]:
out.backward()

In [17]:
print(x.grad)

tensor([[10., 16., 22.],
        [22., 16., 10.]])
